### ISSUE TITLE
細かいデザイン修正

### ISSUE THREAD

**Issue by kogepan159** [juice-inc/rekishoku-web-app#40]
## 見積もり工数
 2時間

## 対応内容
- [ ] 日本語対応
- [x] Search追加
- [x] TabBarの画面遷移変更
- [x] 不必要なパンくずを削除
- [ ] Mapの下のshopListボタンの位置調整

<img width="310" alt="nguniversaldemo" src="https://user-images.githubusercontent.com/7827662/35564258-ea2dd7f6-05fc-11e8-9028-843065376acb.png">

<img width="317" alt="nguniversaldemo2" src="https://user-images.githubusercontent.com/7827662/35564267-f59d63b8-05fc-11e8-85c3-7c55eda095ca.png">

**Comment by hand12** [comment]
現在位置ボタン
