### ISSUE TITLE
ReName対応

### ISSUE THREAD

**Issue by hand12** [juice-inc/rekishoku-web-app#43]
## 見積もり工数
 8時間

現状
    "STORY": "読む",
    "SHOP": "買う",
    "ITEM": "集う",
    "HOME": "ホーム",
    "GROUP": "行く"

こうしたい
    "STORY": "読む",
    ~~"SHOPPING": "買う",~~
    "SHOP": "買う",
    "EVENT": "集う",
    "HOME": "ホーム",
    "GOING": "行く"

**Comment by kogepan159** [comment]
既存のAPIを叩けていることを確認

**Comment by hand12** [comment]
SHOPはSHOPPINGにしなくていい気がしてきました

**Comment by hand12** [comment]
## going/map
![003_go_top-1](https://user-images.githubusercontent.com/15228193/35763127-a363300c-08e8-11e8-9b52-a8d8417bec33.png)

## going/shoplist
![003_go_top-2](https://user-images.githubusercontent.com/15228193/35763123-8b5ce8ae-08e8-11e8-8673-c0b2f869f263.png)

## going/shop/:shop_id
![003_go_detail](https://user-images.githubusercontent.com/15228193/35763147-ec01b982-08e8-11e8-9967-70cd8bf47bf2.png)

## going/search
![003_go_search1](https://user-images.githubusercontent.com/15228193/35763160-2e6cb34e-08e9-11e8-8740-9f6ca4b8e885.png)

**Comment by hand12** [comment]
## shop
![002_shopping_top](https://user-images.githubusercontent.com/15228193/35763169-5440c628-08e9-11e8-9271-02c6f7f24a08.png)

## shoplist
![002_shopping_list](https://user-images.githubusercontent.com/15228193/35763177-78b4fd9e-08e9-11e8-9daf-ef353457065c.png)

## shop/:shop_id
![002_shopping_detail](https://user-images.githubusercontent.com/15228193/35763180-951bcfd0-08e9-11e8-9f8f-0ff95087bfa4.png)

**Comment by hand12** [comment]
「買う」の項目は、お店の「商品を買う」なので、やっぱりSHOPPINGの方が良さそう
"STORY": "読む",
"SHOPPING": "買う",
"EVENT": "集う",
"HOME": "ホーム",
"GOING": "行く"
