### ISSUE TITLE
記事の一覧・詳細

### ISSUE THREAD

**Issue by hand12** [juice-inc/rekishoku-web-app#62]
## 見積もり工数
 10時間

**Comment by hand12** [comment]
![nguniversaldemo 2](https://user-images.githubusercontent.com/15228193/36339691-7954446e-140e-11e8-9665-f8012f8f3aaa.png)

この画像の部分なのですが、記事投稿者の情報がuser_idしか渡って来ていません、、
お手数ですが、userの名前も帰って来るよう変更してもらってもいいですか？

![nguniversaldemo](https://user-images.githubusercontent.com/15228193/36339674-4a0cdb44-140e-11e8-841c-d531193752e5.png)

**Comment by hand12** [comment]
こちらの赤ワクで囲った部分なのですが、APIの項目に入っていないような気がします
![001_read_detail_1_png](https://user-images.githubusercontent.com/15228193/36339842-7f04ae8c-1411-11e8-8021-fba60df8b9cf.png)

https://docs.google.com/spreadsheets/d/1SOVp8dV5n756gxABT_TV0xDhP57A24UExGVJUhWj1Ys/edit#gid=0

**Comment by kogepan159** [comment]
storyAPI仕様のタブがあるのは、お気付きになられたでしょうか？
https://docs.google.com/spreadsheets/d/1SOVp8dV5n756gxABT_TV0xDhP57A24UExGVJUhWj1Ys/edit#gid=2018245407

下記のような位置にございますので、APIを叩いてみて確認してください。
<img width="799" alt="test" src="https://user-images.githubusercontent.com/7827662/36340614-7d4b4bba-1424-11e8-8157-ce8f0f037adb.png">


※ PICKUP系ではimageがない場合もございます。それを加味して作成のほどよろしくお願いします。
post_quotation_urlもなかったら表示しないようにお願いします。
image_quotation_url または quotation_ urlが空の場合は、ライターさんの名前を表示してください

**Comment by hand12** [comment]
詳細APIなのですが、叩くとリダイレクトされ500エラー帰って来ます
確認していただいてもよろしいでしょうか？？
![2018-02-18 22 23 48](https://user-images.githubusercontent.com/15228193/36352323-758ff55c-14fa-11e8-92cd-a4697d300512.png)

**Comment by kogepan159** [comment]
Home画面で何も表示してないです。
<img width="345" alt="nguniversaldemo" src="https://user-images.githubusercontent.com/7827662/36353227-228a0d86-1507-11e8-8812-a62c453e52f6.png">
