### ISSUE TITLE
関連するお店・他のオススメのストーリーの欄が、取得できていない

### ISSUE THREAD

**Issue by hand12** [juice-inc/rekishoku-web-app#73]
## 見積もり工数
 2時間

scrollCallbackメソッドに問題がありそう
![nguniversaldemo](https://user-images.githubusercontent.com/15228193/36339939-5f0e92c6-1413-11e8-8c22-d36097a91a0f.png)

**Comment by kogepan159** [comment]
/api/stories/[id]

の relation の中身を表示するようにご対応お願いいたします
